# Generated by Django 4.0.4 on 2022-05-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_book_year_of_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishinghouse',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
