# Generated by Django 4.0.4 on 2022-05-10 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_publishinghouse_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='num_of_pages',
            new_name='number_of_pages',
        ),
    ]
